[build]
  # The build command to compile your site
  command = "npm run build"
  
  # The directory containing the static assets to publish after building
  publish = "dist"

# Single Page Application (SPA) rewrite rule to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
